name: CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
       docker-compose down
       docker-compose build
       docker-compose up -d
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        API_PORT: ${{ secrets.API_PORT }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
